name: Deploy to Edgio

on:
  push:
  workflow_dispatch:

jobs:
  deploy-to-edgio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm-proxy.fury.io/moovweb/
      - run: npm ci
      - run: npm run edgio:deploy -- --token=$EDGIO_DEPLOY_TOKEN
        env:
          EDGIO_DEPLOY_TOKEN: ${{secrets.LAYER0_DEPLOY_TOKEN}}
      - run: npm run edgio:deploy -- --skip-build --token=$EDGIO_DEPLOY_TOKEN_1
        env:
          EDGIO_DEPLOY_TOKEN_1: ${{secrets.LAYER0_DEPLOY_TOKEN_1}}
      - run: npm run edgio:deploy -- --skip-build --token=$EDGIO_DEPLOY_TOKEN_2
        env:
          EDGIO_DEPLOY_TOKEN_2: ${{secrets.LAYER0_DEPLOY_TOKEN_2}}
